### PR TITLE
#issue149 - created new label

### PR DESCRIPTION
**Pull request by teiclap**
Created the new label EXPORTER-EXT-DTLS-OVER-SCTP

### CODE REVIEW

**Review by gloinul — COMMENTED** [review]
I wonder if the label should be "EXPORTER-DTLS-OVER-SCTP-EXT" instead?

**Comment by teiclap** [comment]
Changed to EXPORTER-DTLS-OVER-SCTP-EXT

**Comment by gloinul** [comment]
So, I think this section needs to be improved to also indicate that this exporter is intended to be used by DTLS and I don't quite understand the criteria for Recommended. Also, the process for IESG approved docs, here needs to be understood. So I think we should send an email to the experts list and ask. 

I also think there are some benefit to make it clearer what is expected to be added to the IANA registry, so if one can make a table with the values to add I think it would be clearer.

I would also recommend that the reference is updated to include also RFC 8447.

**Comment by gloinul** [comment]
So this is intended to resolve #149.

**Comment by emanjon** [comment]
- I added a table to align with the other IANA registrations.
- I added DTLS-OK = Y
- I added Recommended = Y (requires standards action)

**Comment by emanjon** [comment]
The text in the three IANA subsection 8.1, 8.2, and 8.3 are quite different even if they all register a new value in an existing register. It would make sense to align them and more or less use the same text in all of them. This migth be a new issue.

**Review by gloinul — APPROVED** [review]

**Comment by gloinul** [comment]
I will merge this update and create an new issue for the editorial work to stylistic align the IANA Sections.

**Pull request merged**
